name: flutter_map_supercluster_example
description: Example for Flutter Map Supercluster

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_marker_popup:
    git:
      url: https://github.com/pablodelolmo/flutter_map_marker_popup.git
      ref: master
  flutter_map_supercluster:
    path: ../
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf
